// <auto-generated />
using System;
using Masters2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Masters2.Migrations
{
    [DbContext(typeof(Masters2Context))]
    [Migration("20231220001852_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Masters2.Models.TbAnswer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"), 1L, 1);

                    b.Property<string>("AnswerName")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("AnswerId")
                        .HasName("PK__TbAnswer__D4825004F1B63961");

                    b.ToTable("TbAnswers");
                });

            modelBuilder.Entity("Masters2.Models.TbCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("CategoryId")
                        .HasName("PK__TbCatego__19093A0B17C31D47");

                    b.ToTable("TbCategories");
                });

            modelBuilder.Entity("Masters2.Models.TbForm", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormId"), 1L, 1);

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<int?>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FormDate")
                        .HasColumnType("date");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("ResultId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FormId")
                        .HasName("PK__TbForms__FB05B7DD3D638485");

                    b.HasIndex("AnswerId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ResultId");

                    b.ToTable("TbForms");
                });

            modelBuilder.Entity("Masters2.Models.TbQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"), 1L, 1);

                    b.Property<string>("QuestionName")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("QuestionId")
                        .HasName("PK__TbQuesti__0DC06FAC0E1E2092");

                    b.ToTable("TbQuestions");
                });

            modelBuilder.Entity("Masters2.Models.TbResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"), 1L, 1);

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AnswerDate")
                        .HasColumnType("date");

                    b.Property<string>("ResultName")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ResultId")
                        .HasName("PK__TbResult__9769020804F2305D");

                    b.ToTable("TbResult", (string)null);
                });

            modelBuilder.Entity("Masters2.Models.TbForm", b =>
                {
                    b.HasOne("Masters2.Models.TbAnswer", "Answer")
                        .WithMany("TbForms")
                        .HasForeignKey("AnswerId")
                        .HasConstraintName("FK__TbForms__AnswerI__412EB0B6");

                    b.HasOne("Masters2.Models.TbCategory", "Category")
                        .WithMany("TbForms")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__TbForms__Categor__3F466844");

                    b.HasOne("Masters2.Models.TbQuestion", "Question")
                        .WithMany("TbForms")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("FK__TbForms__Questio__403A8C7D");

                    b.HasOne("Masters2.Models.TbResult", "Result")
                        .WithMany("TbForms")
                        .HasForeignKey("ResultId")
                        .HasConstraintName("FK__TbForms__ResultI__4222D4EF");

                    b.Navigation("Answer");

                    b.Navigation("Category");

                    b.Navigation("Question");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Masters2.Models.TbAnswer", b =>
                {
                    b.Navigation("TbForms");
                });

            modelBuilder.Entity("Masters2.Models.TbCategory", b =>
                {
                    b.Navigation("TbForms");
                });

            modelBuilder.Entity("Masters2.Models.TbQuestion", b =>
                {
                    b.Navigation("TbForms");
                });

            modelBuilder.Entity("Masters2.Models.TbResult", b =>
                {
                    b.Navigation("TbForms");
                });
#pragma warning restore 612, 618
        }
    }
}
